### ISSUE TITLE
Outside for the map is doing a fading glitch (L4D2)

### ISSUE THREAD

**Issue by kickturn** [SentientTurtle/RBXLX2VMF#1]
For some reason, the program does a weird fading outside the map if you convert the VMF for l4d2. Skybox on and off doesn't make a difference.

![image](https://user-images.githubusercontent.com/62524115/179328665-890598dd-8a4c-4048-8bac-a71dab66eb60.png)
![image](https://user-images.githubusercontent.com/62524115/179328713-94b05d1c-b695-4321-8f1d-acd22237e680.png)
![image](https://user-images.githubusercontent.com/62524115/179328730-8650e48d-febe-44f4-b2a9-b76caea4ce56.png)

Am I doing something wrong?

**Comment by SentientTurtle** [comment]
If that's only when the player is entirely _outside_ the map, that's default and normal source engine behaviour; Source engine doesn't really have anything to render outside the map and players should never be able to leave the map under normal gameplay. Unlike Roblox, source engine maps are entirely enclosed, not unlike underground dungeons.

If this happens in the playable area of the map, then something has gone wrong. I have not tested if the automatic skybox will work with Left4Dead(2) specifically, it may simply use the wrong texture. I'll have a look at this and see if I can patch that.

Alternatively if you prefer not waiting for a patch, the immediate solution for your map would be to manually build a new (L4D2-compatible) skybox in hammer.

**Comment by kickturn** [comment]
> If this happens in the playable area of the map, then something has gone wrong. I have not tested if the automatic skybox will work with Left4Dead(2) specifically, it may simply use the wrong texture. I'll have a look at this and see if I can patch that.

I'm inside the map, It's hard to see due to that but i'm on the game map if that's what you are saying.


> If that's only when the player is entirely outside the map, that's default and normal source engine behaviour; Source engine doesn't really have anything to render outside the map and players should never be able to leave the map under normal gameplay


This doesn't happen when I just block out the whole map from seeing the void, so I would think this is the reason. I'll try to see if making a new skybox fixes it.

**Comment by SentientTurtle** [comment]
> I have not tested if the automatic skybox will work with Left4Dead(2) specifically, it may simply use the wrong texture. I'll have a look at this and see if I can patch that.

UPDATE: an issue with the skybox specified in the VMF file; Replacing `world` -> `skyname` field with a game-appropriate value (e.g. "sky_l4d_urban01_hdr") will resolve the issue. The texture used on skybox brushes appears to be fine for the Left 4 Dead games.

I'll add a game selection flag to specify appropriate defaults.

**Comment by SentientTurtle** [comment]
Fixed with f647ca7efceb3ed37d4a3aca64386b3ba855d18b.
