### ISSUE TITLE
Website converter never starts because of an error

### ISSUE THREAD

**Issue by Speeder323** [SentientTurtle/RBXLX2VMF#4]
Opening the dev tools console reveals why:
"SyntaxError: import declarations may only appear at top level of a module rbxlx2vmf_worker.js:1"
using Mozilla Firefox 111.0.1 (64-bit)

**Comment by SentientTurtle** [comment]
Good catch. Firefox doesn't support ES module webworkers, that's what I get for not reading the MDN browser support table correctly.

I've pushed a ninja-fix to the github-pages hosted version that works on firefox. 

I'll have a look at a proper fix for the wasm-bindgen output.

**Comment by SentientTurtle** [comment]
Proper fix is up with [8e908d2](https://github.com/SentientTurtle/RBXLX2VMF/commit/8e908d2648a7eeba406129d0b327d3eb9c4ba90a)
