### ISSUE TITLE
textures are not working

### ISSUE THREAD

**Issue by xFN10x** [SentientTurtle/RBXLX2VMF#8]

**Comment by SentientTurtle** [comment]
I cannot help you without more information about what you have tried and for which game you are compiling the map.

Please note the textures provided by this tool are PNG files, you will need to manually convert them to VTF format for source engine to be able to use them.

During blockout/grayboxing, you can also try the 'developer textures' option, which assigns developer textures provided by source engine, skipping the manual image format conversion.

**Comment by xFN10x** [comment]
the game is tf2. also, what are the vmt files already there?

**Comment by SentientTurtle** [comment]
VMT files contain additional texture information. (See https://developer.valvesoftware.com/wiki/VMT )
The 'rbx' folder with both the (manually converted) VTF and VMT files must be copied to the game's material folder. (In TF2's case, "Team Fortress 2\tf\materials", you may discard the PNG files after conversion.

For general source engine mapping help, you're best off asking elsewhere. The hammer editor subreddit or the source engine discord server can answer specific questions, and there are good hammer editor tutorials on youtube if you're completely new to source engine mapping.

**Comment by SentientTurtle** [comment]
As of  e2fc787 the tool now provides VTF format textures, making this manual conversion step no longer necessary.
