### ISSUE TITLE
Way to many numportals.

### ISSUE THREAD

**Issue by xFN10x** [SentientTurtle/RBXLX2VMF#9]
When i try to run the map for tf2, I realize there are 14000 numportals... way to many

**Comment by SentientTurtle** [comment]
Either your map is too complex, or detail objects are not marked as such. 

The tool recognizes certain geometry as detail if, in the roblox editor, either of the following is done:
* Setting the model name to `func_detail` (all lower case)
* Adding a StringValue object to the model whose name or value property is `func_detail`

You can also manually convert VMF brushes to detail in Hammer editor.
